language: go
go:
  - 1.15.x
os:
  - linux
jobs:
  include:
    - script: go vet
    - stage: deploy
      if: tag IS present
      install:
        - curl -fsSL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | BINDIR=$GOPATH/bin sh
      script: skip
      deploy:
        - provider: script
          script: goreleaser
          on:
            tags: true
